seo: 
  site_name: Mido and Tolo
  title: Mido and Tolo
  description: Weâ€™re Ahmed and Sidney, just a couple of big kids sharing their adventures and showing that travel can be accessible.
  keywords: accessible travel, adventure couple
  social_image: 
  author: Sidney
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-text_color: '#023047'
  medium-text_color: '#219EBC'
  light-text_color: '#8ECAE6'
  featured-text_color: '#FFB703'
  dark_color: '#023047'
  medium_color: '#219EBC'
  light_color: '#8ECAE6'
  v-light_color: '#f9f9f9'
  featured_color: '#FFB703'
  accent_color: '#FB8500'
